#
#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

run:
  concurrency: 4
  deadline: 5m
  issues-exit-code: 1
  tests: true
  build-tags: [""]
  skip-dirs:  [""]
  go: '1.19'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  depguard:
    list-type: denylist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
    packages-with-error-message:
      - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - unnamedResult
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
    ignore-words:
      - marshaller
      - marshalling
      - unmarshalling
      - behaviour
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
    machine: false # don't require //nolint instead of // nolint
    explain: false # don't require //nolint // my explanation instead of just //nolint
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

linters:
  enable-all: true
  disable:
   - asciicheck
   - gochecknoglobals
   - gocognit
   - godot
   - godox
   - goerr113
   - prealloc
   - testpackage
   - wsl
   - exhaustive
   - exhaustruct
   - gomoddirectives
   - cyclop
   - ireturn
   - nonamedreturns
   - paralleltest
   - varnamelen
   - wrapcheck
   - tagliatelle
   - maintidx
   - gci
   - containedctx
   - forbidigo
   - musttag
   # The following linters are deprecated:
   - scopelint
   - varcheck
   - deadcode
   - exhaustivestruct
   - maligned
   - structcheck
   - ifshort
   - nosnakecase
   - interfacer
   - golint

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - funlen
        - bodyclose
        - dupl
        - goconst
        - gosec
        - noctx
        - wrapcheck
        - lll

    - path: pkg/golinters/errcheck.go
      text: "SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead"
    - path: pkg/commands/run.go
      text: "SA1019: lsc.Errcheck.Exclude is deprecated: use ExcludeFunctions instead"
    - path: pkg/commands/run.go
      text: "SA1019: e.cfg.Run.Deadline is deprecated: Deadline exists for historical compatibility and should not be used."

    - path: pkg/golinters/gofumpt.go
      text: "SA1019: settings.LangVersion is deprecated: use the global `run.go` instead."
    - path: pkg/golinters/staticcheck_common.go
      text: "SA1019: settings.GoVersion is deprecated: use the global `run.go` instead."
    - path: pkg/lint/lintersdb/manager.go
      text: "SA1019: (.+).(GoVersion|LangVersion) is deprecated: use the global `run.go` instead."

  exclude:
    - \`config\` is a global variable
    -  Line contains TODO/BUG/FIXME
    # Add comments for package
    -  at least one file in a package should have a package comment
    # Allow package logger variables (for now)
    - logger is a global variable

  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments