// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
)

type DIDPublisher struct {
	PublishDIDStub        func(context.Context, string) error
	publishDIDMutex       sync.RWMutex
	publishDIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	publishDIDReturns struct {
		result1 error
	}
	publishDIDReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DIDPublisher) PublishDID(arg1 context.Context, arg2 string) error {
	fake.publishDIDMutex.Lock()
	ret, specificReturn := fake.publishDIDReturnsOnCall[len(fake.publishDIDArgsForCall)]
	fake.publishDIDArgsForCall = append(fake.publishDIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PublishDIDStub
	fakeReturns := fake.publishDIDReturns
	fake.recordInvocation("PublishDID", []interface{}{arg1, arg2})
	fake.publishDIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DIDPublisher) PublishDIDCallCount() int {
	fake.publishDIDMutex.RLock()
	defer fake.publishDIDMutex.RUnlock()
	return len(fake.publishDIDArgsForCall)
}

func (fake *DIDPublisher) PublishDIDCalls(stub func(context.Context, string) error) {
	fake.publishDIDMutex.Lock()
	defer fake.publishDIDMutex.Unlock()
	fake.PublishDIDStub = stub
}

func (fake *DIDPublisher) PublishDIDArgsForCall(i int) (context.Context, string) {
	fake.publishDIDMutex.RLock()
	defer fake.publishDIDMutex.RUnlock()
	argsForCall := fake.publishDIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DIDPublisher) PublishDIDReturns(result1 error) {
	fake.publishDIDMutex.Lock()
	defer fake.publishDIDMutex.Unlock()
	fake.PublishDIDStub = nil
	fake.publishDIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *DIDPublisher) PublishDIDReturnsOnCall(i int, result1 error) {
	fake.publishDIDMutex.Lock()
	defer fake.publishDIDMutex.Unlock()
	fake.PublishDIDStub = nil
	if fake.publishDIDReturnsOnCall == nil {
		fake.publishDIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishDIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DIDPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.publishDIDMutex.RLock()
	defer fake.publishDIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DIDPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
