// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"net/url"
	"sync"
)

type AcceptListMgr struct {
	GetStub        func(target string) ([]*url.URL, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		target string
	}
	getReturns struct {
		result1 []*url.URL
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 []*url.URL
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AcceptListMgr) Get(target string) ([]*url.URL, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		target string
	}{target})
	fake.recordInvocation("Get", []interface{}{target})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(target)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getReturns.result1, fake.getReturns.result2
}

func (fake *AcceptListMgr) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *AcceptListMgr) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].target
}

func (fake *AcceptListMgr) GetReturns(result1 []*url.URL, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 []*url.URL
		result2 error
	}{result1, result2}
}

func (fake *AcceptListMgr) GetReturnsOnCall(i int, result1 []*url.URL, result2 error) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 []*url.URL
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 []*url.URL
		result2 error
	}{result1, result2}
}

func (fake *AcceptListMgr) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AcceptListMgr) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
