// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"net/url"
	"sync"

	"github.com/trustbloc/orb/pkg/activitypub/store/spi"
)

type ReferenceIterator struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	NextStub        func() (*url.URL, error)
	nextMutex       sync.RWMutex
	nextArgsForCall []struct {
	}
	nextReturns struct {
		result1 *url.URL
		result2 error
	}
	nextReturnsOnCall map[int]struct {
		result1 *url.URL
		result2 error
	}
	TotalItemsStub        func() (int, error)
	totalItemsMutex       sync.RWMutex
	totalItemsArgsForCall []struct {
	}
	totalItemsReturns struct {
		result1 int
		result2 error
	}
	totalItemsReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReferenceIterator) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReferenceIterator) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *ReferenceIterator) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *ReferenceIterator) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *ReferenceIterator) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ReferenceIterator) Next() (*url.URL, error) {
	fake.nextMutex.Lock()
	ret, specificReturn := fake.nextReturnsOnCall[len(fake.nextArgsForCall)]
	fake.nextArgsForCall = append(fake.nextArgsForCall, struct {
	}{})
	stub := fake.NextStub
	fakeReturns := fake.nextReturns
	fake.recordInvocation("Next", []interface{}{})
	fake.nextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReferenceIterator) NextCallCount() int {
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	return len(fake.nextArgsForCall)
}

func (fake *ReferenceIterator) NextCalls(stub func() (*url.URL, error)) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = stub
}

func (fake *ReferenceIterator) NextReturns(result1 *url.URL, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	fake.nextReturns = struct {
		result1 *url.URL
		result2 error
	}{result1, result2}
}

func (fake *ReferenceIterator) NextReturnsOnCall(i int, result1 *url.URL, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	if fake.nextReturnsOnCall == nil {
		fake.nextReturnsOnCall = make(map[int]struct {
			result1 *url.URL
			result2 error
		})
	}
	fake.nextReturnsOnCall[i] = struct {
		result1 *url.URL
		result2 error
	}{result1, result2}
}

func (fake *ReferenceIterator) TotalItems() (int, error) {
	fake.totalItemsMutex.Lock()
	ret, specificReturn := fake.totalItemsReturnsOnCall[len(fake.totalItemsArgsForCall)]
	fake.totalItemsArgsForCall = append(fake.totalItemsArgsForCall, struct {
	}{})
	stub := fake.TotalItemsStub
	fakeReturns := fake.totalItemsReturns
	fake.recordInvocation("TotalItems", []interface{}{})
	fake.totalItemsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReferenceIterator) TotalItemsCallCount() int {
	fake.totalItemsMutex.RLock()
	defer fake.totalItemsMutex.RUnlock()
	return len(fake.totalItemsArgsForCall)
}

func (fake *ReferenceIterator) TotalItemsCalls(stub func() (int, error)) {
	fake.totalItemsMutex.Lock()
	defer fake.totalItemsMutex.Unlock()
	fake.TotalItemsStub = stub
}

func (fake *ReferenceIterator) TotalItemsReturns(result1 int, result2 error) {
	fake.totalItemsMutex.Lock()
	defer fake.totalItemsMutex.Unlock()
	fake.TotalItemsStub = nil
	fake.totalItemsReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *ReferenceIterator) TotalItemsReturnsOnCall(i int, result1 int, result2 error) {
	fake.totalItemsMutex.Lock()
	defer fake.totalItemsMutex.Unlock()
	fake.TotalItemsStub = nil
	if fake.totalItemsReturnsOnCall == nil {
		fake.totalItemsReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.totalItemsReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *ReferenceIterator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	fake.totalItemsMutex.RLock()
	defer fake.totalItemsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReferenceIterator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spi.ReferenceIterator = new(ReferenceIterator)
