// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
)

type Discovery struct {
	RequestDiscoveryStub        func(context.Context, string) error
	requestDiscoveryMutex       sync.RWMutex
	requestDiscoveryArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	requestDiscoveryReturns struct {
		result1 error
	}
	requestDiscoveryReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Discovery) RequestDiscovery(arg1 context.Context, arg2 string) error {
	fake.requestDiscoveryMutex.Lock()
	ret, specificReturn := fake.requestDiscoveryReturnsOnCall[len(fake.requestDiscoveryArgsForCall)]
	fake.requestDiscoveryArgsForCall = append(fake.requestDiscoveryArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RequestDiscoveryStub
	fakeReturns := fake.requestDiscoveryReturns
	fake.recordInvocation("RequestDiscovery", []interface{}{arg1, arg2})
	fake.requestDiscoveryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Discovery) RequestDiscoveryCallCount() int {
	fake.requestDiscoveryMutex.RLock()
	defer fake.requestDiscoveryMutex.RUnlock()
	return len(fake.requestDiscoveryArgsForCall)
}

func (fake *Discovery) RequestDiscoveryCalls(stub func(context.Context, string) error) {
	fake.requestDiscoveryMutex.Lock()
	defer fake.requestDiscoveryMutex.Unlock()
	fake.RequestDiscoveryStub = stub
}

func (fake *Discovery) RequestDiscoveryArgsForCall(i int) (context.Context, string) {
	fake.requestDiscoveryMutex.RLock()
	defer fake.requestDiscoveryMutex.RUnlock()
	argsForCall := fake.requestDiscoveryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Discovery) RequestDiscoveryReturns(result1 error) {
	fake.requestDiscoveryMutex.Lock()
	defer fake.requestDiscoveryMutex.Unlock()
	fake.RequestDiscoveryStub = nil
	fake.requestDiscoveryReturns = struct {
		result1 error
	}{result1}
}

func (fake *Discovery) RequestDiscoveryReturnsOnCall(i int, result1 error) {
	fake.requestDiscoveryMutex.Lock()
	defer fake.requestDiscoveryMutex.Unlock()
	fake.RequestDiscoveryStub = nil
	if fake.requestDiscoveryReturnsOnCall == nil {
		fake.requestDiscoveryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.requestDiscoveryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Discovery) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.requestDiscoveryMutex.RLock()
	defer fake.requestDiscoveryMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Discovery) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
