// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	proofa "github.com/trustbloc/orb/pkg/anchor/witness/proof"
)

type VCStatusStore struct {
	AddStatusStub        func(string, proofa.VCStatus) error
	addStatusMutex       sync.RWMutex
	addStatusArgsForCall []struct {
		arg1 string
		arg2 proofa.VCStatus
	}
	addStatusReturns struct {
		result1 error
	}
	addStatusReturnsOnCall map[int]struct {
		result1 error
	}
	GetStatusStub        func(string) (proofa.VCStatus, error)
	getStatusMutex       sync.RWMutex
	getStatusArgsForCall []struct {
		arg1 string
	}
	getStatusReturns struct {
		result1 proofa.VCStatus
		result2 error
	}
	getStatusReturnsOnCall map[int]struct {
		result1 proofa.VCStatus
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *VCStatusStore) AddStatus(arg1 string, arg2 proofa.VCStatus) error {
	fake.addStatusMutex.Lock()
	ret, specificReturn := fake.addStatusReturnsOnCall[len(fake.addStatusArgsForCall)]
	fake.addStatusArgsForCall = append(fake.addStatusArgsForCall, struct {
		arg1 string
		arg2 proofa.VCStatus
	}{arg1, arg2})
	fake.recordInvocation("AddStatus", []interface{}{arg1, arg2})
	fake.addStatusMutex.Unlock()
	if fake.AddStatusStub != nil {
		return fake.AddStatusStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.addStatusReturns
	return fakeReturns.result1
}

func (fake *VCStatusStore) AddStatusCallCount() int {
	fake.addStatusMutex.RLock()
	defer fake.addStatusMutex.RUnlock()
	return len(fake.addStatusArgsForCall)
}

func (fake *VCStatusStore) AddStatusCalls(stub func(string, proofa.VCStatus) error) {
	fake.addStatusMutex.Lock()
	defer fake.addStatusMutex.Unlock()
	fake.AddStatusStub = stub
}

func (fake *VCStatusStore) AddStatusArgsForCall(i int) (string, proofa.VCStatus) {
	fake.addStatusMutex.RLock()
	defer fake.addStatusMutex.RUnlock()
	argsForCall := fake.addStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *VCStatusStore) AddStatusReturns(result1 error) {
	fake.addStatusMutex.Lock()
	defer fake.addStatusMutex.Unlock()
	fake.AddStatusStub = nil
	fake.addStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *VCStatusStore) AddStatusReturnsOnCall(i int, result1 error) {
	fake.addStatusMutex.Lock()
	defer fake.addStatusMutex.Unlock()
	fake.AddStatusStub = nil
	if fake.addStatusReturnsOnCall == nil {
		fake.addStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *VCStatusStore) GetStatus(arg1 string) (proofa.VCStatus, error) {
	fake.getStatusMutex.Lock()
	ret, specificReturn := fake.getStatusReturnsOnCall[len(fake.getStatusArgsForCall)]
	fake.getStatusArgsForCall = append(fake.getStatusArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetStatus", []interface{}{arg1})
	fake.getStatusMutex.Unlock()
	if fake.GetStatusStub != nil {
		return fake.GetStatusStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getStatusReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *VCStatusStore) GetStatusCallCount() int {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return len(fake.getStatusArgsForCall)
}

func (fake *VCStatusStore) GetStatusCalls(stub func(string) (proofa.VCStatus, error)) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = stub
}

func (fake *VCStatusStore) GetStatusArgsForCall(i int) string {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	argsForCall := fake.getStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *VCStatusStore) GetStatusReturns(result1 proofa.VCStatus, result2 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	fake.getStatusReturns = struct {
		result1 proofa.VCStatus
		result2 error
	}{result1, result2}
}

func (fake *VCStatusStore) GetStatusReturnsOnCall(i int, result1 proofa.VCStatus, result2 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	if fake.getStatusReturnsOnCall == nil {
		fake.getStatusReturnsOnCall = make(map[int]struct {
			result1 proofa.VCStatus
			result2 error
		})
	}
	fake.getStatusReturnsOnCall[i] = struct {
		result1 proofa.VCStatus
		result2 error
	}{result1, result2}
}

func (fake *VCStatusStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addStatusMutex.RLock()
	defer fake.addStatusMutex.RUnlock()
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *VCStatusStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
